FLASK_APP=app.py
MONGODB_DB=aes
MONGODB_HOST=mongodb
FLASK_ENV=development
FLASK_RUN_HOST=0.0.0.0
MONGO_URI='mongodb+srv://haliputri:1sampai8@graditer.smz5cee.mongodb.net/graditer'
MAIL_SERVER='smtp.gmail.com'
MAIL_PORT=587
MAIL_USERNAME='akunlainhali@gmail.com'
MAIL_PASSWORD='xvzc dbpr pwhj fwxm'
MAIL_USE_TLS=True
MAIL_USE_SSL=False